### ISSUE TITLE
Replace localforage with direct IndexedDB

### ISSUE THREAD

**Issue by Kukulkano** [DataVaccinator/vaccinatorJSClient#2]
We should replace the localforage library with direct IndexedDB access.

See here for additional details and a possible start:
https://developers.google.com/web/ilt/pwa/working-with-indexeddb

**Note:** Brosers which do not support IndexedDB will not be able to run the DataVaccinator JS class then. The localforage library switches to another database schema in the backend automatically. This will be gone then!

**Comment by DataVaccinator** [comment]
Done
